language: python
python: 2.7
env:
    - TOX_ENV=py27-django18
    - TOX_ENV=py33-django18
    - TOX_ENV=py34-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py33-django19
    - TOX_ENV=py34-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py33-django110
    - TOX_ENV=py34-django110
    - TOX_ENV=flake8
script: tox -e $TOX_ENV
install:
    - pip install tox
